# Site settings 
title: Dean Knox
email: dcknox@upenn.edu
url: http://dcknox.com

description: "... is an assistant professor in at the Wharton School, University
of Pennsylvania. He develops statistical models and methods for policing and other complex social science applications, including audio recordings, decision sequences, and mobile location records."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#464646'
  links: '#97b4db'

# Footer settings
footer: Academic Homepage of Dean Knox

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/dcknox
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=KIIh-2YAAAAJ
  - title: twitter
    url: https://twitter.com/dean_c_knox

# Build settings
markdown: kramdown
permalink: pretty
 
 
 

  